# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c2:6a:c7:6e:77:f0:71:cd:66:00:e0:59:d2:93:a9:2c"
      - run: 
          command: |
            bash install_singularity.sh
            cd /home/circleci/project
            sudo pip install -q pipenv
            pipenv install requests
            pipenv run python get_container_list.py
            # scp singularity_import/*:* singularity@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/singularity/bot/
            # head -n 300 build.sh | tail -n 200 > build2.sh
            bash build.sh
            #scp ./built_containers/*:* singularity@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/singularity/bot/
          no_output_timeout: 3h # takes a while to get the quay containers, hopefully not 3h though
