version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - pip install requests
      - run: python get_container_list.py

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4 
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run
          command: |
            sudo pip install pipenv
            pipenv install requests