# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  singularity: singularity/singularity@1.0.8

jobs:
  build:
    machine:
      image: "circleci/classic:201808-01"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c2:6a:c7:6e:77:f0:71:cd:66:00:e0:59:d2:93:a9:2c"
      - run: 
          command: |
            sudo rm -rf /usr/local/go
            #go get golang.org/dl/go1.12.9
            #go version
            sudo apt-get update && sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
            wget https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzvf go1.12.9.linux-amd64.tar.gz
            rm go1.12.9.linux-amd64.tar.gz
            go get -u github.com/golang/dep/cmd/dep
            go get -d github.com/sylabs/singularity && exit 0
            mkdir -p $HOME/go/src/github.com/sylabs
            cd $HOME/go/src/github.com/sylabs
            wget https://github.com/sylabs/singularity/releases/download/v3.3.0/singularity-3.3.0.tar.gz
            tar -xzf singularity-3.3.0.tar.gz
            cd ./singularity
            ./mconfig
            make -C ./builddir
            sudo make -C ./builddir install
            cd /home/circleci/project
            #sudo wget -q -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
            #sudo apt-key adv --recv-key --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
            #sudo apt-get update -qq
            #sudo apt-get install -y singularity-container
            singularity --version
            sudo pip install pipenv
            pipenv install requests
            pipenv run python get_container_list.py
            # scp singularity_import/*:* singularity@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/singularity/bot/
            head -n 300 build.sh | tail -n 200 > build2.sh
            bash build2.sh
            #scp ./built_containers/*:* singularity@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/singularity/bot/
          no_output_timeout: 3h # takes a while to get the quay containers, hopefully not 3h though
