# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c2:6a:c7:6e:77:f0:71:cd:66:00:e0:59:d2:93:a9:2c"
      - run: 
          command: |
            bash install_singularity.sh
            cd /home/circleci/project
            pip -qq install requests
            python get_container_list.py
            bash build.sh
          no_output_timeout: 3h # takes a while to get the quay containers, hopefully not 3h though


workflows:
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 4,10,16,22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
