name: Singularity container build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    steps:
      - name: Checkout bot code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache downloads
        uses: actions/cache@v1
        with:
          path: |
            ~/.cache/pip
            /usr/local/bin/singularity
            /usr/local/go/
          key: cache-${{ matrix.python-version }}
      - name: Install singularity
        run: |
          bash install_singularity.sh
      - name: Install Python dependencies
        run: |
          python -m pip --requirement requirements.in
      - name: Get list of containers to build
        run: |
          python get_container_list.py
      - name: Build containers
        run: |
          echo "${{ secrets.DEPOT_GALAXYPROJECT_ORG }}" > ssh_key && chmod 600 ssh_key
          cat build.sh
          bash build.sh
