name: Singularity container build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPOT_GALAXYPROJECT_ORG }}

      - name: Cache downloads
        uses: actions/cache@v1
        with:
          path: |
            ~/.cache/pip
            /usr/local/bin/singularity
            /usr/local/go/
          key: cache-${{ matrix.python-version }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          bash install_singularity.sh
          cd /home/circleci/project
          pip -qq install requests
          python get_container_list.py
          bash build.sh
