name: Build Singularity images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
        singularity-version:
          - '3.8.3'
    steps:
      - name: Checkout bot code
        uses: actions/checkout@v3
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}_Python-${{ matrix.python-version }}_Singularity-${{ matrix.singularity-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --requirement requirements.in
      - name: Fetch images and generate build script
        run: |
          ./populate_build.py
      - name: Set up Singularity ${{ matrix.singularity-version }}
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: ${{ matrix.singularity-version }}
      - name: Build images
        run: |
          echo "${{ secrets.DEPOT_GALAXYPROJECT_ORG }}" > ssh_key && chmod 600 ssh_key
          ./build.sh
